name: CI

on:
    push:
        branches:
            - main
            - next
        paths-ignore:
            - ".changeset/**"
            - README.md
            - ".vscode/**"
            - CHANGELOG.md
    pull_request:
        paths-ignore:
            - ".changeset/**"
            - README.md
            - ".vscode/**"
            - CHANGELOG.md

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
    Check:
        name: Run typecheck
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile --prefer-offline

            - name: Run typecheck
              run: pnpm typecheck

    Lint:
        runs-on: macos-latest
        name: Lint
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile --prefer-offline

            - run: pnpm lint

    Test:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile --prefer-offline

            - name: Run tests
              run: pnpm test